### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by brianteeman** [dgrammatiko/joomla-extension-templates#5]
Thought I would give this a try because I am having a problem with an admin module of mine not displaying the xml_description string on install. I figured I could try this and find my mistake by comparing.

Unfortunately the one thing this script doesnt do is to create the language entries in the xml file

**Comment by dgrammatiko** [comment]
Good catch, I would update the XMLs that are missing the language entry

**Comment by brianteeman** [comment]
Some docs would be nice as well ;)

**Comment by dgrammatiko** [comment]
Should be fixed now.

The docs are a WIP
