### ISSUE TITLE
template name

### ISSUE THREAD

**Issue by brianteeman** [dgrammatiko/joomla-extension-templates#6]
![image](https://user-images.githubusercontent.com/1296369/236450014-d9cc51ad-ec0b-4845-93eb-e7ba00c475ad.png)

I assume that it should say "lowercase" alphanumeric

**Comment by dgrammatiko** [comment]
I guess the validation needs some attention. PRs welcome: https://github.com/dgrammatiko/create-joomla-extension/blob/f7412a0040bdfc63306ef14d55ab21ace751515c/lib/utils/utils.mjs#L11

**Comment by dgrammatiko** [comment]
Should be fixed now, thanks
